import Head from 'next/head'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import { CheckCircleIcon } from '@chakra-ui/icons'
import { Flex, Heading, Stack, Card, List, Center, CardBody, ListIcon, ListItem, Text, CardFooter, Button, CardHeader } from '@chakra-ui/react'
import Image from 'next/image'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Stack  >
        <div className={styles.containerOne}>
          <Heading color="#F7FAFC" as='h2' size={['lg', 'xl']} mt="10%" ml={[5, 0]} textAlign={["start", "center"]}>
            Simple pricing for your business
          </Heading>
          <Heading color="#F7FAFC" as='h5' size='sm' mt="1%" ml={[5, 0]} textAlign={["start", "center"]}>
            Plans that are carefully crafted to suit your business.
          </Heading>
        </div>
        <div className={styles.containerTwo}>
          <Card
            direction={{ base: 'column', sm: 'row' }}
            overflow='hidden'
            variant='outline'
            mr={[5, 200]}
            ml={[5, 200]}
            mt={-100}
          >
            <Card className={styles.card} >
              <div className={styles.priceBgColor} />
              <CardHeader >
                <Heading size='md' mt="10%">Premium PRO</Heading>
              </CardHeader>
              <CardBody>
                <Heading as='h2' size='3xl' mt="-10%">$329</Heading>
                <Heading as='h5' size='sm' mt="5%">billed just once</Heading>
              </CardBody>
              <CardFooter>
                <Button width="100%" variant='solid' bgColor="#805AD5" color="#ffffff" mt="-5%" mb="10%">
                  Get Started
                </Button>
              </CardFooter>
            </Card>
            <Stack>
              <CardBody>
                <Text m="5">  Access these features when you get this pricing package for your business.</Text>
                <List spacing={5} m="5">
                  <ListItem >
                    <ListIcon as={CheckCircleIcon} color='#805AD5' />
                    International calling and messaging API
                  </ListItem>
                  <ListItem>
                    <ListIcon as={CheckCircleIcon} color='#805AD5' />
                    Additional phone numbers
                  </ListItem>
                  <ListItem>
                    <ListIcon as={CheckCircleIcon} color='#805AD5' />
                    Automated messages via Zapier
                  </ListItem>
                  {/* You can also use custom icons from react-icons */}
                  <ListItem>
                    <ListIcon as={CheckCircleIcon} color='#805AD5' />
                    24/7 support and consulting
                  </ListItem>
                </List>
              </CardBody>
            </Stack>
          </Card>
          <Flex mt="10" mb="20" flexDirection={["column", "row"]} mr={[5, 400]}
            ml={[5, 400]}>
            <Center flex='1'>
              <Image width={60} height={60} className={styles.imageOne} src="/one.png" alt="one" />
              <Text fontWeight="bold">30 days money back Guarantee</Text>
            </Center>
            <Center flex='1' >
              <Image width={60} height={60} className={styles.imageTwo} src="/two.png" alt="one" />
              <Text fontWeight="bold">No setup fees
                100% hassle-free</Text>
            </Center>
            <Center flex='1' >
              <Image width={80} height={80} className={styles.imageThree} src="/three.png" alt="one" />
              <Text fontWeight="bold">No monthly subscription
                Pay once and for all</Text>
            </Center>
          </Flex>
        </div>
      </Stack>
    </>
  )
}
